### ISSUE TITLE
A declaration issue in `runtime.d.ts`

### ISSUE THREAD

**Issue by xiaozs** [piotr-oles/as-loader#21]
`__newArray`‘s declaration in `runtime.d.ts`
```ts
__newArray<T extends ArrayLike<T>>(id: number, values: T): Pointer<T>;
```
should be
```ts
__newArray<T extends ArrayLike<any>>(id: number, values: T): Pointer<T>;
```

**Comment by piotr-oles** [comment]
Thanks for reporting these issues, PR with the fix is on the way. Feel free to open PRs if you notice something wrong :)
